#ifndef FILE_spectra_tree_nodes_operations_Nova_Operator_NOVA
#define FILE_spectra_tree_nodes_operations_Nova_Operator_NOVA

typedef struct spectra_tree_nodes_operations_Nova_Operator spectra_tree_nodes_operations_Nova_Operator;
typedef struct spectra_tree_nodes_operations_Nova_OperatorFunctionMap spectra_tree_nodes_operations_Nova_OperatorFunctionMap;
typedef struct spectra_tree_nodes_operations_Nova_OperatorPropertyMap spectra_tree_nodes_operations_Nova_OperatorPropertyMap;


#include <Nova.h>
#include <InterfaceVTable.h>
#include <ExceptionHandler.h>
#include <nova/exception/nova_exception_Nova_ExceptionData.h>
#include <nova/exception/nova_exception_Nova_Exception.h>
#include <nova/exception/nova_exception_Nova_DivideByZeroException.h>
#include <nova/io/nova_io_Nova_Console.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Number.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Byte.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Short.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Int.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Long.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Float.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Double.h>
#include <nova/primitive/nova_primitive_Nova_Null.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Char.h>
#include <nova/primitive/nova_primitive_Nova_Bool.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_List.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_Array.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_ImmutableArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_IntArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_CharArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_DoubleArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_IntRange.h>
#include <nova/thread/nova_thread_Nova_Thread.h>
#include <nova/thread/async/nova_thread_async_Nova_Async.h>
#include <nova/thread/async/nova_thread_async_Nova_Task.h>
#include <nova/gc/nova_gc_Nova_GC.h>
#include <nova/math/nova_math_Nova_Math.h>
#include <nova/nova_Nova_Object.h>
#include <nova/nova_Nova_String.h>
#include <nova/nova_Nova_System.h>
#include <nova/meta/nova_meta_Nova_Class.h>
#include <nova/meta/nova_meta_Nova_FunctionMap.h>
#include <nova/meta/nova_meta_Nova_PropertyMap.h>
#include <nova/regex/nova_regex_Nova_Pattern.h>
#include <spectra/tree/nodes/spectra_tree_nodes_Nova_Node.h>
#include <spectra/util/spectra_util_Nova_Location.h>
#include <spectra/tree/nodes/spectra_tree_nodes_Nova_Node.h>
#include <spectra/tree/nodes/spectra_tree_nodes_Nova_Node.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_ArrayIterator.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_CharArrayIterator.h>
#include <spectra/spectra_Nova_InvalidParseException.h>
#include <spectra/spectra_Nova_SyntaxErrorException.h>
#include <spectra/error/spectra_error_Nova_UnimplementedOperationException.h>
#include <spectra/tree/nodes/annotations/spectra_tree_nodes_annotations_Nova_Annotatable.h>
#include <spectra/tree/nodes/annotations/spectra_tree_nodes_annotations_Nova_Annotation.h>
#include <spectra/tree/nodes/exceptionhandling/spectra_tree_nodes_exceptionhandling_Nova_Try.h>
#include <spectra/tree/nodes/functions/spectra_tree_nodes_functions_Nova_FunctionDeclaration.h>
#include <spectra/tree/nodes/functions/spectra_tree_nodes_functions_Nova_FunctionCall.h>
#include <spectra/tree/nodes/functions/spectra_tree_nodes_functions_Nova_Instantiation.h>
#include <spectra/tree/nodes/functions/closures/spectra_tree_nodes_functions_closures_Nova_LambdaExpression.h>
#include <spectra/tree/nodes/variables/spectra_tree_nodes_variables_Nova_VariableDeclaration.h>
#include <spectra/tree/nodes/spectra_tree_nodes_Nova_ClassDeclaration.h>
#include <spectra/tree/nodes/spectra_tree_nodes_Nova_NodeList.h>
#include <spectra/tree/nodes/spectra_tree_nodes_Nova_NovaFile.h>
#include <spectra/tree/nodes/spectra_tree_nodes_Nova_PlaceholderValue.h>
#include <spectra/tree/nodes/spectra_tree_nodes_Nova_Program.h>
#include <spectra/tree/nodes/spectra_tree_nodes_Nova_Scope.h>
#include <spectra/tree/nodes/spectra_tree_nodes_Nova_ValidationResult.h>
#include <spectra/tree/nodes/annotations/spectra_tree_nodes_annotations_Nova_Annotatable.h>
#include <spectra/tree/nodes/annotations/spectra_tree_nodes_annotations_Nova_Annotatable.h>
#include <nova/NativeObject.h>

CCLASS_CLASS
(
	spectra_tree_nodes_operations_Nova_Operator, 
	
	spectra_tree_nodes_operations_Operator_Extension_VTable* vtable;
	spectra_util_Nova_Location* spectra_tree_nodes_Nova_Node_Nova_location;
	nova_datastruct_list_Nova_Array* spectra_tree_nodes_Nova_Node_Nova_annotations;
	spectra_tree_nodes_Nova_Node* spectra_tree_nodes_Nova_Node_Nova_parent;
	nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_value;
)
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_AND;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_OR;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_DIVIDE;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_MULTIPLY;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_MODULO;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_ADD;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SUBTRACT;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_ASSIGN;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_BANG;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_EQUALS;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_NOT_EQUAL;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_INCREMENT;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_DECREMENT;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_BITWISE_AND;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_BITWISE_OR;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_BITWISE_XOR;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_BITWISE_COMPLEMENT;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_GREATER;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_LESS;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_GREATER_EQ;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_LESS_EQ;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_L_SHIFT;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_R_SHIFT;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_UR_SHIFT;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SAFE_NAVIGATION;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SHORTHAND_DIVIDE;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SHORTHAND_MULTIPLY;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SHORTHAND_MODULO;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SHORTHAND_ADD;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SHORTHAND_SUBTRACT;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SHORTHAND_BITWISE_AND;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SHORTHAND_BITWISE_OR;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SHORTHAND_BITWISE_XOR;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SHORTHAND_L_SHIFT;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SHORTHAND_R_SHIFT;
extern nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_SHORTHAND_UR_SHIFT;
extern nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_Operator_Nova_OPERATORS;
extern nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_Operator_Nova_UNARY_OPERATORS;
extern nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_Operator_Nova_UNARY_OPERATORS_NO_MINUS;
extern nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_Operator_Nova_MINUS;
extern nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_Operator_Nova_BINARY_OPERATORS;
extern nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_Operator_Nova_LOGICAL_OPERATORS;
extern nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_Operator_Nova_SHORTHAND_OPERATORS;
extern nova_datastruct_list_Nova_CharArray* spectra_tree_nodes_operations_Nova_Operator_Nova_OPERATOR_SYMBOLS;
extern nova_datastruct_list_Nova_CharArray* spectra_tree_nodes_operations_Nova_Operator_Nova_UNARY_OPERATOR_CHARS;

void spectra_tree_nodes_operations_Nova_Operator_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
spectra_tree_nodes_operations_Nova_Operator* spectra_tree_nodes_operations_Nova_Operator_Nova_construct(spectra_tree_nodes_operations_Nova_Operator* this, nova_exception_Nova_ExceptionData* exceptionData, spectra_tree_nodes_Nova_Node* parent, spectra_util_Nova_Location* location, nova_Nova_String* value);
void spectra_tree_nodes_operations_Nova_Operator_Nova_destroy(spectra_tree_nodes_operations_Nova_Operator** this, nova_exception_Nova_ExceptionData* exceptionData);
void spectra_tree_nodes_operations_Nova_Operator_Nova_this(spectra_tree_nodes_operations_Nova_Operator* this, nova_exception_Nova_ExceptionData* exceptionData, spectra_tree_nodes_Nova_Node* parent, spectra_util_Nova_Location* location, nova_Nova_String* value);
nova_Nova_String* spectra_tree_nodes_operations_Nova_Operator_Nova_writeNova(spectra_tree_nodes_operations_Nova_Operator* this, nova_exception_Nova_ExceptionData* exceptionData);
void spectra_tree_nodes_operations_Nova_Operator_Nova_super(spectra_tree_nodes_operations_Nova_Operator* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	spectra_tree_nodes_operations_Nova_OperatorFunctionMap, 
	
	spectra_tree_nodes_operations_Operator_OperatorFunctionMap_Extension_VTable* vtable;
)

void spectra_tree_nodes_operations_Nova_OperatorFunctionMap_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
spectra_tree_nodes_operations_Nova_OperatorFunctionMap* spectra_tree_nodes_operations_Nova_OperatorFunctionMap_Nova_construct(spectra_tree_nodes_operations_Nova_OperatorFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void spectra_tree_nodes_operations_Nova_OperatorFunctionMap_Nova_destroy(spectra_tree_nodes_operations_Nova_OperatorFunctionMap** this, nova_exception_Nova_ExceptionData* exceptionData);
void spectra_tree_nodes_operations_Nova_OperatorFunctionMap_Nova_this(spectra_tree_nodes_operations_Nova_OperatorFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
spectra_tree_nodes_operations_Nova_Operator* spectra_tree_nodes_operations_Nova_OperatorFunctionMap_functionMapOperatorFunctionMap_Nova_construct(spectra_tree_nodes_operations_Nova_OperatorFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, spectra_tree_nodes_Nova_Node* parent, spectra_util_Nova_Location* location, nova_Nova_String* value);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorFunctionMap_functionMap_Nova_writeNova(spectra_tree_nodes_operations_Nova_OperatorFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, spectra_tree_nodes_operations_Nova_Operator* reference);
void spectra_tree_nodes_operations_Nova_OperatorFunctionMap_Nova_super(spectra_tree_nodes_operations_Nova_OperatorFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	spectra_tree_nodes_operations_Nova_OperatorPropertyMap, 
	
	spectra_tree_nodes_operations_Operator_OperatorPropertyMap_Extension_VTable* vtable;
)

void spectra_tree_nodes_operations_Nova_OperatorPropertyMap_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
spectra_tree_nodes_operations_Nova_OperatorPropertyMap* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_Nova_construct(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void spectra_tree_nodes_operations_Nova_OperatorPropertyMap_Nova_destroy(spectra_tree_nodes_operations_Nova_OperatorPropertyMap** this, nova_exception_Nova_ExceptionData* exceptionData);
void spectra_tree_nodes_operations_Nova_OperatorPropertyMap_Nova_this(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_Nova_value(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData, spectra_tree_nodes_operations_Nova_Operator* reference);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_AND(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_OR(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_DIVIDE(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_MULTIPLY(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_MODULO(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_ADD(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SUBTRACT(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_ASSIGN(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_BANG(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_EQUALS(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_NOT_EQUAL(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_INCREMENT(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_DECREMENT(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_BITWISE_AND(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_BITWISE_OR(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_BITWISE_XOR(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_BITWISE_COMPLEMENT(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_GREATER(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_LESS(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_GREATER_EQ(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_LESS_EQ(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_L_SHIFT(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_R_SHIFT(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_UR_SHIFT(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SAFE_NAVIGATION(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SHORTHAND_DIVIDE(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SHORTHAND_MULTIPLY(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SHORTHAND_MODULO(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SHORTHAND_ADD(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SHORTHAND_SUBTRACT(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SHORTHAND_BITWISE_AND(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SHORTHAND_BITWISE_OR(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SHORTHAND_BITWISE_XOR(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SHORTHAND_L_SHIFT(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SHORTHAND_R_SHIFT(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SHORTHAND_UR_SHIFT(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_OPERATORS(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_UNARY_OPERATORS(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_UNARY_OPERATORS_NO_MINUS(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_MINUS(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_BINARY_OPERATORS(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_LOGICAL_OPERATORS(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_Array* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_SHORTHAND_OPERATORS(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_CharArray* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_OPERATOR_SYMBOLS(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_CharArray* spectra_tree_nodes_operations_Nova_OperatorPropertyMap_functionMap_static_Nova_UNARY_OPERATOR_CHARS(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void spectra_tree_nodes_operations_Nova_OperatorPropertyMap_Nova_super(spectra_tree_nodes_operations_Nova_OperatorPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);

#endif
