#ifndef NOVA_INTERFACE_VTABLE
#define NOVA_INTERFACE_VTABLE

typedef struct nova_datastruct_Nova_Comparable nova_datastruct_Nova_Comparable;
typedef struct nova_exception_Nova_ExceptionData nova_exception_Nova_ExceptionData;
typedef struct nova_Nova_Object nova_Nova_Object;
typedef struct nova_Nova_String nova_Nova_String;
typedef struct nova_datastruct_list_Nova_Iterable nova_datastruct_list_Nova_Iterable;
typedef struct nova_datastruct_list_Nova_Iterator nova_datastruct_list_Nova_Iterator;
typedef struct nova_datastruct_list_Nova_IterablePropertyMap nova_datastruct_list_Nova_IterablePropertyMap;
typedef struct nova_datastruct_list_Nova_IteratorPropertyMap nova_datastruct_list_Nova_IteratorPropertyMap;
typedef struct nova_datastruct_list_Nova_List nova_datastruct_list_Nova_List;
typedef struct nova_datastruct_list_Nova_Array nova_datastruct_list_Nova_Array;
typedef struct nova_datastruct_list_Nova_ListFunctionMap nova_datastruct_list_Nova_ListFunctionMap;
typedef struct nova_datastruct_list_Nova_ListPropertyMap nova_datastruct_list_Nova_ListPropertyMap;
typedef struct nova_io_Nova_InputStream nova_io_Nova_InputStream;
typedef struct nova_operators_Nova_EqualsOperator nova_operators_Nova_EqualsOperator;
typedef struct nova_operators_Nova_MultiplyEqualsOperator nova_operators_Nova_MultiplyEqualsOperator;
typedef struct nova_operators_Nova_MultiplyOperator nova_operators_Nova_MultiplyOperator;
typedef struct nova_operators_Nova_NotEqualToOperator nova_operators_Nova_NotEqualToOperator;
typedef struct nova_operators_Nova_PlusEqualsOperator nova_operators_Nova_PlusEqualsOperator;
typedef struct nova_operators_Nova_PlusOperator nova_operators_Nova_PlusOperator;
typedef struct spectra_tree_nodes_Nova_Abstractable spectra_tree_nodes_Nova_Abstractable;
typedef struct spectra_tree_nodes_Nova_Node spectra_tree_nodes_Nova_Node;
typedef struct spectra_tree_nodes_annotations_Nova_Annotatable spectra_tree_nodes_annotations_Nova_Annotatable;
typedef struct spectra_tree_nodes_annotations_Nova_Annotation spectra_tree_nodes_annotations_Nova_Annotation;
typedef struct spectra_tree_nodes_Nova_Value spectra_tree_nodes_Nova_Value;
typedef struct spectra_util_Nova_Location spectra_util_Nova_Location;
typedef struct spectra_tree_nodes_variables_Nova_VariableDeclaration spectra_tree_nodes_variables_Nova_VariableDeclaration;
typedef struct spectra_tree_nodes_Nova_NodeList spectra_tree_nodes_Nova_NodeList;
typedef struct spectra_tree_nodes_Nova_Accessible spectra_tree_nodes_Nova_Accessible;
typedef struct spectra_tree_nodes_Nova_NodeFunctionMap spectra_tree_nodes_Nova_NodeFunctionMap;
typedef struct spectra_tree_nodes_Nova_ValueFunctionMap spectra_tree_nodes_Nova_ValueFunctionMap;
typedef struct spectra_tree_nodes_Nova_ValuePropertyMap spectra_tree_nodes_Nova_ValuePropertyMap;
typedef struct spectra_tree_nodes_annotations_Nova_AnnotatablePropertyMap spectra_tree_nodes_annotations_Nova_AnnotatablePropertyMap;
typedef struct spectra_tree_nodes_Nova_Type spectra_tree_nodes_Nova_Type;
typedef struct spectra_tree_nodes_Nova_NodePropertyMap spectra_tree_nodes_Nova_NodePropertyMap;
typedef struct spectra_tree_nodes_Nova_Program spectra_tree_nodes_Nova_Program;
typedef struct spectra_tree_nodes_functions_Nova_Instantiation spectra_tree_nodes_functions_Nova_Instantiation;
typedef struct spectra_tree_nodes_functions_closures_Nova_LambdaExpression spectra_tree_nodes_functions_closures_Nova_LambdaExpression;
typedef struct spectra_tree_nodes_Nova_NovaFile spectra_tree_nodes_Nova_NovaFile;
typedef struct spectra_tree_nodes_functions_Nova_FunctionCall spectra_tree_nodes_functions_Nova_FunctionCall;
typedef struct spectra_tree_nodes_functions_Nova_FunctionDeclaration spectra_tree_nodes_functions_Nova_FunctionDeclaration;
typedef struct spectra_tree_nodes_exceptionhandling_Nova_Try spectra_tree_nodes_exceptionhandling_Nova_Try;
typedef struct spectra_tree_nodes_Nova_ClassDeclaration spectra_tree_nodes_Nova_ClassDeclaration;
typedef struct spectra_tree_nodes_Nova_Scope spectra_tree_nodes_Nova_Scope;
typedef struct spectra_tree_nodes_annotations_Nova_Modifier spectra_tree_nodes_annotations_Nova_Modifier;
typedef struct nova_datastruct_list_Nova_ImmutableArray nova_datastruct_list_Nova_ImmutableArray;
typedef struct spectra_tree_nodes_annotations_Nova_AnnotationFunctionMap spectra_tree_nodes_annotations_Nova_AnnotationFunctionMap;
typedef struct spectra_tree_nodes_annotations_Nova_ModifierPropertyMap spectra_tree_nodes_annotations_Nova_ModifierPropertyMap;
typedef struct spectra_tree_nodes_annotations_Nova_AnnotationPropertyMap spectra_tree_nodes_annotations_Nova_AnnotationPropertyMap;
typedef struct spectra_tree_nodes_functions_Nova_CallableFunction spectra_tree_nodes_functions_Nova_CallableFunction;
typedef struct spectra_tree_nodes_functions_Nova_Parameter spectra_tree_nodes_functions_Nova_Parameter;
typedef struct spectra_tree_nodes_functions_Nova_ParameterList spectra_tree_nodes_functions_Nova_ParameterList;
typedef struct spectra_tree_nodes_functions_Nova_CallableFunctionFunctionMap spectra_tree_nodes_functions_Nova_CallableFunctionFunctionMap;
typedef struct spectra_tree_nodes_generics_Nova_GenericCompatible spectra_tree_nodes_generics_Nova_GenericCompatible;
typedef struct spectra_tree_nodes_operations_Nova_Assignable spectra_tree_nodes_operations_Nova_Assignable;
typedef struct spectra_tree_nodes_operations_Nova_AssignableFunctionMap spectra_tree_nodes_operations_Nova_AssignableFunctionMap;
typedef struct example_Nova_Polygon example_Nova_Polygon;
typedef char (*nova_Nova_String_closure0_Nova_transform)(void*, nova_exception_Nova_ExceptionData*, char, int, void*);
typedef char (*nova_Nova_String_closure1_Nova_transform)(void*, nova_exception_Nova_ExceptionData*, char, int, void*);
typedef char (*nova_Nova_String_closure2_Nova_transform)(void*, nova_exception_Nova_ExceptionData*, char, int, void*);
typedef char (*nova_Nova_String_closure3_Nova_transform)(void*, nova_exception_Nova_ExceptionData*, char, int, void*);
typedef char (*nova_Nova_StringFunctionMap_closure276_Nova_transform)(void*, nova_exception_Nova_ExceptionData*, char, int, void*);
typedef struct nova_datastruct_Nova_Pair nova_datastruct_Nova_Pair;
typedef char (*nova_datastruct_Nova_HashMap_closure5_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure6_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure7_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure8_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure9_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure10_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure11_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure12_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef struct nova_datastruct_Nova_HashMap nova_datastruct_Nova_HashMap;
typedef nova_Nova_Object* (*nova_datastruct_Nova_HashMap_closure13_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_HashMap_closure14_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_HashMap_closure15_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_HashMap_closure16_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure17_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure18_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure19_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure20_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure21_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure22_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure23_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_HashMap_closure24_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef void (*nova_datastruct_Nova_HashMap_closure25_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef void (*nova_datastruct_Nova_HashMap_closure26_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef void (*nova_datastruct_Nova_HashMap_closure27_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef void (*nova_datastruct_Nova_HashMap_closure28_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_HashMapFunctionMap_closure277_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_HashMapFunctionMap_closure278_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_HashMapFunctionMap_closure279_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_HashMapFunctionMap_closure280_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_HashMapFunctionMap_closure281_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef void (*nova_datastruct_Nova_HashMapFunctionMap_closure282_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure29_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure30_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure31_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure32_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure33_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure34_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure35_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure36_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef struct nova_datastruct_Nova_HashSet nova_datastruct_Nova_HashSet;
typedef nova_Nova_Object* (*nova_datastruct_Nova_HashSet_closure37_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_HashSet_closure38_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_HashSet_closure39_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_HashSet_closure40_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure41_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure42_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure43_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure44_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure45_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure46_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure47_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef char (*nova_datastruct_Nova_HashSet_closure48_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef void (*nova_datastruct_Nova_HashSet_closure49_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef void (*nova_datastruct_Nova_HashSet_closure50_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef void (*nova_datastruct_Nova_HashSet_closure51_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef void (*nova_datastruct_Nova_HashSet_closure52_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef char (*nova_datastruct_Nova_HashSetFunctionMap_closure283_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef char (*nova_datastruct_Nova_HashSetFunctionMap_closure284_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_HashSetFunctionMap_closure285_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef char (*nova_datastruct_Nova_HashSetFunctionMap_closure286_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef char (*nova_datastruct_Nova_HashSetFunctionMap_closure287_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, void*);
typedef void (*nova_datastruct_Nova_HashSetFunctionMap_closure288_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_operators_Nova_EqualsOperator*, int, nova_datastruct_Nova_HashSet*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure53_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure54_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure55_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure56_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure57_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure58_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure59_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure60_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_ImmutableHashMap_closure61_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_ImmutableHashMap_closure62_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_ImmutableHashMap_closure63_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_ImmutableHashMap_closure64_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure65_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure66_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure67_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure68_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure69_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure70_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure71_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMap_closure72_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef void (*nova_datastruct_Nova_ImmutableHashMap_closure73_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef void (*nova_datastruct_Nova_ImmutableHashMap_closure74_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef void (*nova_datastruct_Nova_ImmutableHashMap_closure75_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef void (*nova_datastruct_Nova_ImmutableHashMap_closure76_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMapFunctionMap_closure289_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMapFunctionMap_closure290_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_ImmutableHashMapFunctionMap_closure291_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMapFunctionMap_closure292_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef char (*nova_datastruct_Nova_ImmutableHashMapFunctionMap_closure293_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, void*);
typedef void (*nova_datastruct_Nova_ImmutableHashMapFunctionMap_closure294_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_datastruct_Nova_Pair*, int, nova_datastruct_Nova_HashMap*, void*);
typedef void (*nova_datastruct_Nova_Tuple_closure77_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef void (*nova_datastruct_Nova_Tuple_closure78_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef void (*nova_datastruct_Nova_Tuple_closure79_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef void (*nova_datastruct_Nova_Tuple_closure80_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure81_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure82_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure83_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure84_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure85_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure86_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure87_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure88_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure89_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure90_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure91_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure92_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure93_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure94_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure95_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_Tuple_closure96_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_Tuple_closure97_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_Tuple_closure98_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_Tuple_closure99_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_Tuple_closure100_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef void (*nova_datastruct_Nova_TupleFunctionMap_closure295_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef char (*nova_datastruct_Nova_TupleFunctionMap_closure296_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_TupleFunctionMap_closure297_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_Nova_TupleFunctionMap_closure298_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_Nova_TupleFunctionMap_closure299_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef nova_Nova_Object* (*nova_datastruct_Nova_TupleFunctionMap_closure300_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_Array_closure101_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_Array_closure102_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_Array_closure103_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_Array_closure104_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef void (*nova_datastruct_list_Nova_Array_closure105_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef void (*nova_datastruct_list_Nova_Array_closure106_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef void (*nova_datastruct_list_Nova_Array_closure107_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef void (*nova_datastruct_list_Nova_Array_closure108_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_list_Nova_Array_closure109_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_list_Nova_Array_closure110_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_list_Nova_Array_closure111_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_list_Nova_Array_closure112_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef double (*nova_datastruct_list_Nova_Array_closure113_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_Array*, void*);
typedef double (*nova_datastruct_list_Nova_Array_closure114_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_Array*, void*);
typedef double (*nova_datastruct_list_Nova_Array_closure115_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_Array*, void*);
typedef double (*nova_datastruct_list_Nova_Array_closure116_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_Array*, void*);
typedef int (*nova_datastruct_list_Nova_Array_closure117_Nova_comparator)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_Array_closure118_Nova_comparator)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_Array_closure119_Nova_comparator)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_Array_closure120_Nova_comparator)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_Array_closure121_Nova_comparator)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_Array_closure122_Nova_comparator)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_Array_closure123_Nova_comparator)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_Array_closure124_Nova_comparator)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, nova_Nova_Object*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_ArrayFunctionMap_closure301_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef void (*nova_datastruct_list_Nova_ArrayFunctionMap_closure302_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_list_Nova_ArrayFunctionMap_closure303_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef double (*nova_datastruct_list_Nova_ArrayFunctionMap_closure304_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_Array*, void*);
typedef int (*nova_datastruct_list_Nova_ArrayFunctionMap_closure305_Nova_comparator)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_ArrayFunctionMap_closure306_Nova_comparator)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, nova_Nova_Object*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_ImmutableArray_closure133_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_ImmutableArray_closure134_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_ImmutableArray_closure135_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_ImmutableArray_closure136_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef void (*nova_datastruct_list_Nova_ImmutableArray_closure137_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef void (*nova_datastruct_list_Nova_ImmutableArray_closure138_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef void (*nova_datastruct_list_Nova_ImmutableArray_closure139_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef void (*nova_datastruct_list_Nova_ImmutableArray_closure140_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_list_Nova_ImmutableArray_closure141_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_list_Nova_ImmutableArray_closure142_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_list_Nova_ImmutableArray_closure143_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_list_Nova_ImmutableArray_closure144_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_ImmutableArrayFunctionMap_closure309_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef void (*nova_datastruct_list_Nova_ImmutableArrayFunctionMap_closure310_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef char (*nova_datastruct_list_Nova_ImmutableArrayFunctionMap_closure311_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_Array*, void*);
typedef struct nova_datastruct_list_Nova_LinkedList nova_datastruct_list_Nova_LinkedList;
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_LinkedList_closure145_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_LinkedList_closure146_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_LinkedList_closure147_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_LinkedList_closure148_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef void (*nova_datastruct_list_Nova_LinkedList_closure149_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef void (*nova_datastruct_list_Nova_LinkedList_closure150_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef void (*nova_datastruct_list_Nova_LinkedList_closure151_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef void (*nova_datastruct_list_Nova_LinkedList_closure152_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure153_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure154_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure155_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure156_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure157_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure158_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure159_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure160_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure161_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure162_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure163_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure164_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure165_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure166_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure167_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedList_closure168_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_LinkedListFunctionMap_closure312_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef void (*nova_datastruct_list_Nova_LinkedListFunctionMap_closure313_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedListFunctionMap_closure314_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedListFunctionMap_closure315_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedListFunctionMap_closure316_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_LinkedList*, void*);
typedef char (*nova_datastruct_list_Nova_LinkedListFunctionMap_closure317_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef void (*nova_datastruct_list_Nova_List_closure169_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef void (*nova_datastruct_list_Nova_List_closure170_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef void (*nova_datastruct_list_Nova_List_closure171_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef void (*nova_datastruct_list_Nova_List_closure172_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure173_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure174_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure175_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure176_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure177_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure178_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure179_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure180_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure181_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure182_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure183_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure184_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure185_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure186_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure187_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure188_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef int (*nova_datastruct_list_Nova_List_closure189_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_List_closure190_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_List_closure191_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_List_closure192_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_List_closure193_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_List_closure194_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_List_closure195_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_List_closure196_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure197_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure198_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure199_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_List_closure200_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure201_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure202_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure203_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure204_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef struct OtherType OtherType;
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure205_Nova_zipper)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, OtherType*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure206_Nova_zipper)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, OtherType*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure207_Nova_zipper)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, OtherType*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure208_Nova_zipper)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, OtherType*, void*);
typedef struct Out Out;
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure209_Nova_func)(void*, nova_exception_Nova_ExceptionData*, Out*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure210_Nova_func)(void*, nova_exception_Nova_ExceptionData*, Out*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure211_Nova_func)(void*, nova_exception_Nova_ExceptionData*, Out*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_List_closure212_Nova_func)(void*, nova_exception_Nova_ExceptionData*, Out*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef void (*nova_datastruct_list_Nova_ListFunctionMap_closure318_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_ListFunctionMap_closure319_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef char (*nova_datastruct_list_Nova_ListFunctionMap_closure320_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_ListFunctionMap_closure321_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef char (*nova_datastruct_list_Nova_ListFunctionMap_closure322_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef int (*nova_datastruct_list_Nova_ListFunctionMap_closure323_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef int (*nova_datastruct_list_Nova_ListFunctionMap_closure324_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef char (*nova_datastruct_list_Nova_ListFunctionMap_closure325_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_ListFunctionMap_closure326_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_ListFunctionMap_closure327_Nova_zipper)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, nova_Nova_Object*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_ListFunctionMap_closure328_Nova_func)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, nova_Nova_Object*, int, nova_datastruct_list_Nova_List*, void*);
typedef struct nova_datastruct_list_Nova_OrderedList nova_datastruct_list_Nova_OrderedList;
typedef char (*nova_datastruct_list_Nova_OrderedList_closure213_Nova_condition)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_OrderedList*, void*);
typedef char (*nova_datastruct_list_Nova_OrderedList_closure214_Nova_condition)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_OrderedList*, void*);
typedef char (*nova_datastruct_list_Nova_OrderedList_closure215_Nova_condition)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_OrderedList*, void*);
typedef char (*nova_datastruct_list_Nova_OrderedList_closure216_Nova_condition)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_OrderedList*, void*);
typedef char (*nova_datastruct_list_Nova_OrderedListFunctionMap_closure329_Nova_condition)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*, int, nova_datastruct_list_Nova_OrderedList*, void*);
typedef void (*nova_thread_Nova_Thread_closure218_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_Nova_Thread_closure219_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_Nova_Thread_closure220_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_Nova_Thread_closure221_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_Nova_ThreadFunctionMap_closure330_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_async_Nova_Async_closure222_Nova_func)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_async_Nova_Async_closure223_Nova_func)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_async_Nova_Async_closure224_Nova_func)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_async_Nova_Async_closure225_Nova_func)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_async_Nova_Async_closure226_Nova_func)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_async_Nova_Async_closure227_Nova_func)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_async_Nova_Async_closure228_Nova_func)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_async_Nova_Async_closure229_Nova_func)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_async_Nova_AsyncFunctionMap_closure331_Nova_func)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_thread_async_Nova_AsyncFunctionMap_closure332_Nova_func)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_time_Nova_Timer_closure230_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef struct nova_time_Nova_Timer nova_time_Nova_Timer;
typedef void (*nova_time_Nova_Timer_closure231_Nova_callback)(void*, nova_exception_Nova_ExceptionData*, nova_time_Nova_Timer*, void*);
typedef void (*nova_time_Nova_Timer_closure232_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_time_Nova_Timer_closure233_Nova_callback)(void*, nova_exception_Nova_ExceptionData*, nova_time_Nova_Timer*, void*);
typedef void (*nova_time_Nova_Timer_closure234_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_time_Nova_Timer_closure235_Nova_callback)(void*, nova_exception_Nova_ExceptionData*, nova_time_Nova_Timer*, void*);
typedef void (*nova_time_Nova_Timer_closure236_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_time_Nova_Timer_closure237_Nova_callback)(void*, nova_exception_Nova_ExceptionData*, nova_time_Nova_Timer*, void*);
typedef void (*nova_time_Nova_TimerFunctionMap_closure333_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*nova_time_Nova_TimerFunctionMap_closure334_Nova_callback)(void*, nova_exception_Nova_ExceptionData*, nova_time_Nova_Timer*, void*);
typedef void (*spectra_tree_Nova_SyntaxTree_closure238_Nova_func)(void*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_NovaFile*, void*);
typedef void (*spectra_tree_Nova_SyntaxTree_closure239_Nova_func)(void*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_NovaFile*, void*);
typedef void (*spectra_tree_Nova_SyntaxTree_closure240_Nova_func)(void*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_NovaFile*, void*);
typedef void (*spectra_tree_Nova_SyntaxTree_closure241_Nova_func)(void*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_NovaFile*, void*);
typedef void (*spectra_tree_Nova_SyntaxTreeFunctionMap_closure335_Nova_func)(void*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_NovaFile*, void*);
typedef void (*spectra_tree_nodes_Nova_Node_closure242_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*spectra_tree_nodes_Nova_Node_closure243_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*spectra_tree_nodes_Nova_Node_closure244_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*spectra_tree_nodes_Nova_Node_closure245_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*spectra_tree_nodes_Nova_Node_closure246_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*spectra_tree_nodes_Nova_Node_closure247_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*spectra_tree_nodes_Nova_Node_closure248_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*spectra_tree_nodes_Nova_Node_closure249_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*spectra_tree_nodes_Nova_NodeFunctionMap_closure336_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef void (*spectra_tree_nodes_Nova_NodeFunctionMap_closure337_Nova_action)(void*, nova_exception_Nova_ExceptionData*, void*);
typedef int (*spectra_util_Nova_CompilerStringFunctions_closure250_Nova_advance)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_String*, char, int, int, void*);
typedef int (*spectra_util_Nova_CompilerStringFunctions_closure251_Nova_advance)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_String*, char, int, int, void*);

typedef struct nova_Interface_VTable
{
int (*nova_datastruct_Nova_Comparable_virtual0_Nova_compareTo)(nova_datastruct_Nova_Comparable*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*);
nova_Nova_Object* (*nova_Nova_Object_virtual_static_Nova_default)(nova_Nova_Object*, nova_exception_Nova_ExceptionData*);
nova_Nova_String* (*nova_Nova_Object_virtual_Nova_toString)(nova_Nova_Object*, nova_exception_Nova_ExceptionData*);
nova_datastruct_list_Nova_Iterator* (*nova_datastruct_list_Nova_Iterable_virtual_Accessorfunc_Nova_iterator)(nova_datastruct_list_Nova_Iterable*, nova_exception_Nova_ExceptionData*);
nova_datastruct_list_Nova_Iterator* (*nova_datastruct_list_Nova_Iterable_virtual_Mutatorfunc_Nova_iterator)(nova_datastruct_list_Nova_Iterable*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_Iterator*);
nova_datastruct_list_Nova_Iterator* (*nova_datastruct_list_Nova_IterablePropertyMap_virtualfunctionMap2_Nova_iterator)(nova_datastruct_list_Nova_IterablePropertyMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_Iterable*);
char (*nova_datastruct_list_Nova_Iterator_virtual_Accessorfunc_Nova_hasNext)(nova_datastruct_list_Nova_Iterator*, nova_exception_Nova_ExceptionData*);
nova_Nova_Object* (*nova_datastruct_list_Nova_Iterator_virtual_Accessor_Nova_next)(nova_datastruct_list_Nova_Iterator*, nova_exception_Nova_ExceptionData*);
char (*nova_datastruct_list_Nova_IteratorPropertyMap_virtualfunctionMap0_Nova_hasNext)(nova_datastruct_list_Nova_IteratorPropertyMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_Iterator*);
nova_Nova_Object* (*nova_datastruct_list_Nova_IteratorPropertyMap_virtualfunctionMap0_Nova_next)(nova_datastruct_list_Nova_IteratorPropertyMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_Iterator*);
nova_datastruct_list_Nova_Array* (*nova_datastruct_list_Nova_List_virtual_Nova_toArray)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*);
char (*nova_datastruct_list_Nova_List_virtual0_Nova_contains)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*);
nova_datastruct_list_Nova_List* (*nova_datastruct_list_Nova_List_virtual0_Nova_forEach)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List_closure172_Nova_func nova_datastruct_list_Nova_List_Nova_func, void* nova_datastruct_list_Nova_List_ref_Nova_func, void* func_context);
nova_datastruct_list_Nova_List* (*nova_datastruct_list_Nova_List_virtual0_Nova_map)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List_closure176_Nova_mapFunc nova_datastruct_list_Nova_List_Nova_mapFunc, void* nova_datastruct_list_Nova_List_ref_Nova_mapFunc, void* mapFunc_context);
char (*nova_datastruct_list_Nova_List_virtual0_Nova_any)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List_closure180_Nova_anyFunc nova_datastruct_list_Nova_List_Nova_anyFunc, void* nova_datastruct_list_Nova_List_ref_Nova_anyFunc, void* anyFunc_context);
char (*nova_datastruct_list_Nova_List_virtual0_Nova_all)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List_closure184_Nova_allFunc nova_datastruct_list_Nova_List_Nova_allFunc, void* nova_datastruct_list_Nova_List_ref_Nova_allFunc, void* allFunc_context, int);
nova_datastruct_list_Nova_List* (*nova_datastruct_list_Nova_List_virtual0_Nova_filter)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List_closure188_Nova_filterFunc nova_datastruct_list_Nova_List_Nova_filterFunc, void* nova_datastruct_list_Nova_List_ref_Nova_filterFunc, void* filterFunc_context);
nova_datastruct_list_Nova_List* (*nova_datastruct_list_Nova_List_virtual_Nova_take)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, int);
nova_datastruct_list_Nova_List* (*nova_datastruct_list_Nova_List_virtual_Nova_skip)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, int);
nova_Nova_Object* (*nova_datastruct_list_Nova_List_virtual0_Nova_firstWhere)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List_closure200_Nova_func nova_datastruct_list_Nova_List_Nova_func, void* nova_datastruct_list_Nova_List_ref_Nova_func, void* func_context);
nova_datastruct_list_Nova_List* (*nova_datastruct_list_Nova_List_virtual_Nova_reverse)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*);
nova_Nova_String* (*nova_datastruct_list_Nova_List_virtual_Nova_join)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, nova_Nova_String*);
int (*nova_datastruct_list_Nova_List_virtual_Accessorfunc_Nova_count)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*);
int (*nova_datastruct_list_Nova_List_virtual_Mutatorfunc_Nova_count)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, int);
nova_Nova_Object* (*nova_datastruct_list_Nova_List_virtual_Accessorfunc_Nova_first)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*);
nova_Nova_Object* (*nova_datastruct_list_Nova_List_virtual_Mutatorfunc_Nova_first)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*);
nova_Nova_Object* (*nova_datastruct_list_Nova_List_virtual_Accessor_Nova_last)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*);
nova_Nova_Object* (*nova_datastruct_list_Nova_List_virtual_Mutator_Nova_last)(nova_datastruct_list_Nova_List*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*);
nova_datastruct_list_Nova_Array* (*nova_datastruct_list_Nova_ListFunctionMap_virtualfunctionMap0_Nova_toArray)(nova_datastruct_list_Nova_ListFunctionMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*);
char (*nova_datastruct_list_Nova_ListFunctionMap_virtualfunctionMap0_Nova_contains)(nova_datastruct_list_Nova_ListFunctionMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*, nova_Nova_Object*);
nova_datastruct_list_Nova_List* (*nova_datastruct_list_Nova_ListFunctionMap_virtualfunctionMap0_Nova_forEach)(nova_datastruct_list_Nova_ListFunctionMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*, nova_datastruct_list_Nova_ListFunctionMap_closure318_Nova_func nova_datastruct_list_Nova_ListFunctionMap_Nova_func, void* nova_datastruct_list_Nova_ListFunctionMap_ref_Nova_func, void* func_context);
nova_datastruct_list_Nova_List* (*nova_datastruct_list_Nova_ListFunctionMap_virtualfunctionMap0_Nova_map)(nova_datastruct_list_Nova_ListFunctionMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*, nova_datastruct_list_Nova_ListFunctionMap_closure319_Nova_mapFunc nova_datastruct_list_Nova_ListFunctionMap_Nova_mapFunc, void* nova_datastruct_list_Nova_ListFunctionMap_ref_Nova_mapFunc, void* mapFunc_context);
char (*nova_datastruct_list_Nova_ListFunctionMap_virtualfunctionMap0_Nova_any)(nova_datastruct_list_Nova_ListFunctionMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*, nova_datastruct_list_Nova_ListFunctionMap_closure320_Nova_anyFunc nova_datastruct_list_Nova_ListFunctionMap_Nova_anyFunc, void* nova_datastruct_list_Nova_ListFunctionMap_ref_Nova_anyFunc, void* anyFunc_context);
char (*nova_datastruct_list_Nova_ListFunctionMap_virtualfunctionMap0_Nova_all)(nova_datastruct_list_Nova_ListFunctionMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*, nova_datastruct_list_Nova_ListFunctionMap_closure321_Nova_allFunc nova_datastruct_list_Nova_ListFunctionMap_Nova_allFunc, void* nova_datastruct_list_Nova_ListFunctionMap_ref_Nova_allFunc, void* allFunc_context, char);
nova_datastruct_list_Nova_List* (*nova_datastruct_list_Nova_ListFunctionMap_virtualfunctionMap0_Nova_filter)(nova_datastruct_list_Nova_ListFunctionMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*, nova_datastruct_list_Nova_ListFunctionMap_closure322_Nova_filterFunc nova_datastruct_list_Nova_ListFunctionMap_Nova_filterFunc, void* nova_datastruct_list_Nova_ListFunctionMap_ref_Nova_filterFunc, void* filterFunc_context);
nova_datastruct_list_Nova_List* (*nova_datastruct_list_Nova_ListFunctionMap_virtualfunctionMap0_Nova_take)(nova_datastruct_list_Nova_ListFunctionMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*, int);
nova_datastruct_list_Nova_List* (*nova_datastruct_list_Nova_ListFunctionMap_virtualfunctionMap0_Nova_skip)(nova_datastruct_list_Nova_ListFunctionMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*, int);
nova_Nova_Object* (*nova_datastruct_list_Nova_ListFunctionMap_virtualfunctionMap0_Nova_firstWhere)(nova_datastruct_list_Nova_ListFunctionMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*, nova_datastruct_list_Nova_ListFunctionMap_closure325_Nova_func nova_datastruct_list_Nova_ListFunctionMap_Nova_func, void* nova_datastruct_list_Nova_ListFunctionMap_ref_Nova_func, void* func_context);
nova_Nova_String* (*nova_datastruct_list_Nova_ListFunctionMap_virtualfunctionMap0_Nova_join)(nova_datastruct_list_Nova_ListFunctionMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*, nova_Nova_String*);
nova_Nova_String* (*nova_datastruct_list_Nova_ListFunctionMap_virtualfunctionMap0_Nova_toString)(nova_datastruct_list_Nova_ListFunctionMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*);
int (*nova_datastruct_list_Nova_ListPropertyMap_virtualfunctionMap0_Nova_count)(nova_datastruct_list_Nova_ListPropertyMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*);
nova_Nova_Object* (*nova_datastruct_list_Nova_ListPropertyMap_virtualfunctionMap0_Nova_first)(nova_datastruct_list_Nova_ListPropertyMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*);
nova_Nova_Object* (*nova_datastruct_list_Nova_ListPropertyMap_virtualfunctionMap0_Nova_last)(nova_datastruct_list_Nova_ListPropertyMap*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_List*);
nova_Nova_String* (*nova_io_Nova_InputStream_virtual_Nova_readString)(nova_io_Nova_InputStream*, nova_exception_Nova_ExceptionData*);
nova_datastruct_list_Nova_Array* (*nova_io_Nova_InputStream_virtual_Nova_readBytes)(nova_io_Nova_InputStream*, nova_exception_Nova_ExceptionData*);
char (*nova_operators_Nova_EqualsOperator_virtual0_Nova_equals)(nova_operators_Nova_EqualsOperator*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*);
nova_Nova_Object* (*nova_operators_Nova_MultiplyEqualsOperator_virtual_Nova_multiplyEquals)(nova_operators_Nova_MultiplyEqualsOperator*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*);
nova_Nova_Object* (*nova_operators_Nova_MultiplyOperator_virtual0_Nova_multiply)(nova_operators_Nova_MultiplyOperator*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*);
char (*nova_operators_Nova_NotEqualToOperator_virtual_Nova_notEqualTo)(nova_operators_Nova_NotEqualToOperator*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*);
nova_Nova_Object* (*nova_operators_Nova_PlusEqualsOperator_virtual0_Nova_plusEquals)(nova_operators_Nova_PlusEqualsOperator*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*);
nova_Nova_Object* (*nova_operators_Nova_PlusOperator_virtual0_Nova_plus)(nova_operators_Nova_PlusOperator*, nova_exception_Nova_ExceptionData*, nova_Nova_Object*);
char (*spectra_tree_nodes_Nova_Abstractable_virtual_Accessorfunc_Nova_isAbstract)(spectra_tree_nodes_Nova_Abstractable*, nova_exception_Nova_ExceptionData*);
char (*spectra_tree_nodes_Nova_Abstractable_virtual_Mutatorfunc_Nova_isAbstract)(spectra_tree_nodes_Nova_Abstractable*, nova_exception_Nova_ExceptionData*, char);
spectra_tree_nodes_Nova_Node* (*spectra_tree_nodes_Nova_Node_virtual_Nova_cloneTo)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
void (*spectra_tree_nodes_annotations_Nova_Annotatable_virtual_Nova_addAnnotation)(spectra_tree_nodes_annotations_Nova_Annotatable*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_annotations_Nova_Annotation*);
spectra_tree_nodes_Nova_Value* (*spectra_tree_nodes_Nova_Value_virtual0_static_Nova_parse)(spectra_tree_nodes_Nova_Value*, nova_exception_Nova_ExceptionData*, nova_Nova_String*, spectra_tree_nodes_Nova_Node*, spectra_util_Nova_Location*, int);
char (*spectra_tree_nodes_Nova_Value_virtual_Nova_parseType)(spectra_tree_nodes_Nova_Value*, nova_exception_Nova_ExceptionData*, nova_Nova_String*);
char (*spectra_tree_nodes_Nova_Node_virtual_Nova_validateTypes)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*);
nova_Nova_String* (*spectra_tree_nodes_Nova_Value_virtual_Nova_writeType)(spectra_tree_nodes_Nova_Value*, nova_exception_Nova_ExceptionData*);
void (*spectra_tree_nodes_Nova_Node_virtual_Nova_addChild)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
void (*spectra_tree_nodes_Nova_Node_virtual_Nova_onAdded)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_variables_Nova_VariableDeclaration* (*spectra_tree_nodes_Nova_Node_virtual_Nova_findVariableDeclaration)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*, nova_Nova_String*, int);
spectra_tree_nodes_Nova_Node* (*spectra_tree_nodes_Nova_Node_virtual_Nova_parseStatement)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*, nova_Nova_String*, spectra_tree_nodes_Nova_Node*, spectra_util_Nova_Location*, int);
spectra_tree_nodes_Nova_Node* (*spectra_tree_nodes_Nova_Node_virtual_Nova_generateTemporaryScopeNode)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*);
char (*spectra_tree_nodes_Nova_Node_virtual_Nova_replace)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*, spectra_tree_nodes_Nova_Node*);
char (*spectra_tree_nodes_Nova_Node_virtual_Nova_parsePlaceholders)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*);
char (*spectra_tree_nodes_Nova_Node_virtual_Nova_parsePlaceholderChildren)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_NodeList*);
nova_Nova_String* (*spectra_tree_nodes_Nova_Node_virtual_Nova_writeAnnotationSeparator)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*);
nova_Nova_String* (*spectra_tree_nodes_Nova_Node_virtual_Nova_toNova)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*);
nova_Nova_String* (*spectra_tree_nodes_Nova_Node_virtual_Nova_writeNova)(spectra_tree_nodes_Nova_Node*, nova_exception_Nova_ExceptionData*);
spectra_tree_nodes_Nova_Accessible* (*spectra_tree_nodes_Nova_Value_virtual_Accessor_Nova_returnedNode)(spectra_tree_nodes_Nova_Value*, nova_exception_Nova_ExceptionData*);
char (*spectra_tree_nodes_Nova_Accessible_virtual_Accessorfunc_Nova_safeNavigation)(spectra_tree_nodes_Nova_Accessible*, nova_exception_Nova_ExceptionData*);
char (*spectra_tree_nodes_Nova_Accessible_virtual_Mutatorfunc_Nova_safeNavigation)(spectra_tree_nodes_Nova_Accessible*, nova_exception_Nova_ExceptionData*, char);
spectra_tree_nodes_Nova_Accessible* (*spectra_tree_nodes_Nova_Accessible_virtual_Accessor_Nova_accessedNode)(spectra_tree_nodes_Nova_Accessible*, nova_exception_Nova_ExceptionData*);
spectra_tree_nodes_Nova_Accessible* (*spectra_tree_nodes_Nova_Accessible_virtual_Mutator_Nova_accessedNode)(spectra_tree_nodes_Nova_Accessible*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Accessible*);
spectra_tree_nodes_Nova_Node* (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_cloneTo)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_Nova_Value* (*spectra_tree_nodes_Nova_ValueFunctionMap_virtualfunctionMap0_static_Nova_parse)(spectra_tree_nodes_Nova_ValueFunctionMap*, nova_exception_Nova_ExceptionData*, nova_Nova_String*, spectra_tree_nodes_Nova_Node*, spectra_util_Nova_Location*, char);
char (*spectra_tree_nodes_Nova_ValueFunctionMap_virtualfunctionMap_Nova_parseType)(spectra_tree_nodes_Nova_ValueFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Value*, nova_Nova_String*);
char (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_validateTypes)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
nova_Nova_String* (*spectra_tree_nodes_Nova_ValueFunctionMap_virtualfunctionMap_Nova_writeType)(spectra_tree_nodes_Nova_ValueFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Value*);
spectra_tree_nodes_Nova_Node* (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMapNode_Nova_construct)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*, spectra_util_Nova_Location*);
void (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_addChild)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*, spectra_tree_nodes_Nova_Node*);
void (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_onAdded)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_variables_Nova_VariableDeclaration* (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_findVariableDeclaration)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*, nova_Nova_String*, char);
spectra_tree_nodes_Nova_Node* (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_parseStatement)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*, nova_Nova_String*, spectra_tree_nodes_Nova_Node*, spectra_util_Nova_Location*, char);
spectra_tree_nodes_Nova_Node* (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_generateTemporaryScopeNode)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
char (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_replace)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*, spectra_tree_nodes_Nova_Node*, spectra_tree_nodes_Nova_Node*);
char (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_parsePlaceholders)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
char (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_parsePlaceholderChildren)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*, spectra_tree_nodes_Nova_NodeList*);
nova_Nova_String* (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_writeAnnotationSeparator)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
nova_Nova_String* (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_toNova)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
nova_Nova_String* (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_writeNova)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
nova_Nova_String* (*spectra_tree_nodes_Nova_NodeFunctionMap_virtualfunctionMap_Nova_toString)(spectra_tree_nodes_Nova_NodeFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_Nova_Accessible* (*spectra_tree_nodes_Nova_ValuePropertyMap_virtualfunctionMap_Nova_returnedNode)(spectra_tree_nodes_Nova_ValuePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Value*);
nova_datastruct_list_Nova_Array* (*spectra_tree_nodes_annotations_Nova_AnnotatablePropertyMap_virtualfunctionMap0_Nova_annotations)(spectra_tree_nodes_annotations_Nova_AnnotatablePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_annotations_Nova_Annotatable*);
spectra_tree_nodes_Nova_Type* (*spectra_tree_nodes_Nova_ValuePropertyMap_virtualfunctionMap_Nova_type)(spectra_tree_nodes_Nova_ValuePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Value*);
char (*spectra_tree_nodes_Nova_ValuePropertyMap_virtualfunctionMap_Nova_isAssignable)(spectra_tree_nodes_Nova_ValuePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Value*);
spectra_tree_nodes_Nova_Program* (*spectra_tree_nodes_Nova_NodePropertyMap_virtualfunctionMap_Nova_program)(spectra_tree_nodes_Nova_NodePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_functions_Nova_Instantiation* (*spectra_tree_nodes_Nova_NodePropertyMap_virtualfunctionMap_Nova_parentInstantiation)(spectra_tree_nodes_Nova_NodePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_functions_closures_Nova_LambdaExpression* (*spectra_tree_nodes_Nova_NodePropertyMap_virtualfunctionMap_Nova_parentLambda)(spectra_tree_nodes_Nova_NodePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_Nova_NovaFile* (*spectra_tree_nodes_Nova_NodePropertyMap_virtualfunctionMap_Nova_parentFile)(spectra_tree_nodes_Nova_NodePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_functions_Nova_FunctionCall* (*spectra_tree_nodes_Nova_NodePropertyMap_virtualfunctionMap_Nova_parentFunctionCall)(spectra_tree_nodes_Nova_NodePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_functions_Nova_FunctionDeclaration* (*spectra_tree_nodes_Nova_NodePropertyMap_virtualfunctionMap_Nova_parentFunction)(spectra_tree_nodes_Nova_NodePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_exceptionhandling_Nova_Try* (*spectra_tree_nodes_Nova_NodePropertyMap_virtualfunctionMap_Nova_parentTry)(spectra_tree_nodes_Nova_NodePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_Nova_ClassDeclaration* (*spectra_tree_nodes_Nova_NodePropertyMap_virtualfunctionMap_Nova_parentClass)(spectra_tree_nodes_Nova_NodePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_Nova_Node* (*spectra_tree_nodes_Nova_NodePropertyMap_virtualfunctionMap_Nova_scopeConsumer)(spectra_tree_nodes_Nova_NodePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_Nova_Scope* (*spectra_tree_nodes_Nova_NodePropertyMap_virtualfunctionMap_Nova_scope)(spectra_tree_nodes_Nova_NodePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
int (*spectra_tree_nodes_Nova_NodePropertyMap_virtualfunctionMap_Nova_index)(spectra_tree_nodes_Nova_NodePropertyMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*);
spectra_tree_nodes_annotations_Nova_Annotation* (*spectra_tree_nodes_annotations_Nova_Annotation_virtual1_static_Nova_parse)(spectra_tree_nodes_annotations_Nova_Annotation*, nova_exception_Nova_ExceptionData*, nova_Nova_String*, nova_Nova_String*, spectra_tree_nodes_Nova_Node*, spectra_util_Nova_Location*, int);
char (*spectra_tree_nodes_annotations_Nova_Annotation_virtual_Nova_onApplied)(spectra_tree_nodes_annotations_Nova_Annotation*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*, int);
char (*spectra_tree_nodes_annotations_Nova_Annotation_virtual_Nova_checkApplication)(spectra_tree_nodes_annotations_Nova_Annotation*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Node*, int);
nova_Nova_String* (*spectra_tree_nodes_annotations_Nova_Modifier_virtual_Accessorfunc_Nova_alias)(spectra_tree_nodes_annotations_Nova_Modifier*, nova_exception_Nova_ExceptionData*);
nova_Nova_String* (*spectra_tree_nodes_annotations_Nova_Modifier_virtual_Mutatorfunc_Nova_alias)(spectra_tree_nodes_annotations_Nova_Modifier*, nova_exception_Nova_ExceptionData*, nova_Nova_String*);
nova_datastruct_list_Nova_ImmutableArray* (*spectra_tree_nodes_annotations_Nova_Modifier_virtual_Accessor_static_Nova_aliases)(spectra_tree_nodes_annotations_Nova_Modifier*, nova_exception_Nova_ExceptionData*);
spectra_tree_nodes_annotations_Nova_Annotation* (*spectra_tree_nodes_annotations_Nova_AnnotationFunctionMap_virtualfunctionMap1_static_Nova_parse)(spectra_tree_nodes_annotations_Nova_AnnotationFunctionMap*, nova_exception_Nova_ExceptionData*, nova_Nova_String*, nova_Nova_String*, spectra_tree_nodes_Nova_Node*, spectra_util_Nova_Location*, char);
char (*spectra_tree_nodes_annotations_Nova_AnnotationFunctionMap_virtualfunctionMap_Nova_onApplied)(spectra_tree_nodes_annotations_Nova_AnnotationFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_annotations_Nova_Annotation*, spectra_tree_nodes_Nova_Node*, char);
char (*spectra_tree_nodes_annotations_Nova_AnnotationFunctionMap_virtualfunctionMap_Nova_checkApplication)(spectra_tree_nodes_annotations_Nova_AnnotationFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_annotations_Nova_Annotation*, spectra_tree_nodes_Nova_Node*, char);
nova_datastruct_list_Nova_ImmutableArray* (*spectra_tree_nodes_annotations_Nova_ModifierPropertyMap_virtualfunctionMap_static_Nova_aliases)(spectra_tree_nodes_annotations_Nova_ModifierPropertyMap*, nova_exception_Nova_ExceptionData*);
nova_datastruct_list_Nova_ImmutableArray* (*spectra_tree_nodes_annotations_Nova_AnnotationPropertyMap_virtualfunctionMap_static_Nova_applicationTypes)(spectra_tree_nodes_annotations_Nova_AnnotationPropertyMap*, nova_exception_Nova_ExceptionData*);
nova_datastruct_list_Nova_ImmutableArray* (*spectra_tree_nodes_annotations_Nova_Annotation_virtual_Accessor_static_Nova_applicationTypes)(spectra_tree_nodes_annotations_Nova_Annotation*, nova_exception_Nova_ExceptionData*);
spectra_tree_nodes_functions_Nova_Parameter* (*spectra_tree_nodes_functions_Nova_CallableFunction_virtual_Nova_parseParameter)(spectra_tree_nodes_functions_Nova_CallableFunction*, nova_exception_Nova_ExceptionData*, nova_Nova_String*, int);
char (*spectra_tree_nodes_functions_Nova_CallableFunction_virtual_Nova_parseParameters)(spectra_tree_nodes_functions_Nova_CallableFunction*, nova_exception_Nova_ExceptionData*, nova_Nova_String*, int);
spectra_tree_nodes_functions_Nova_ParameterList* (*spectra_tree_nodes_functions_Nova_CallableFunction_virtual_Accessorfunc_Nova_parameterList)(spectra_tree_nodes_functions_Nova_CallableFunction*, nova_exception_Nova_ExceptionData*);
spectra_tree_nodes_functions_Nova_ParameterList* (*spectra_tree_nodes_functions_Nova_CallableFunction_virtual_Mutatorfunc_Nova_parameterList)(spectra_tree_nodes_functions_Nova_CallableFunction*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_functions_Nova_ParameterList*);
spectra_tree_nodes_functions_Nova_Parameter* (*spectra_tree_nodes_functions_Nova_CallableFunctionFunctionMap_virtualfunctionMap0_Nova_parseParameter)(spectra_tree_nodes_functions_Nova_CallableFunctionFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_functions_Nova_CallableFunction*, nova_Nova_String*, char);
char (*spectra_tree_nodes_functions_Nova_CallableFunctionFunctionMap_virtualfunctionMap0_Nova_parseParameters)(spectra_tree_nodes_functions_Nova_CallableFunctionFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_functions_Nova_CallableFunction*, nova_Nova_String*, char);
nova_datastruct_list_Nova_Array* (*spectra_tree_nodes_generics_Nova_GenericCompatible_virtual_Accessorfunc_Nova_genericParameters)(spectra_tree_nodes_generics_Nova_GenericCompatible*, nova_exception_Nova_ExceptionData*);
nova_datastruct_list_Nova_Array* (*spectra_tree_nodes_generics_Nova_GenericCompatible_virtual_Mutatorfunc_Nova_genericParameters)(spectra_tree_nodes_generics_Nova_GenericCompatible*, nova_exception_Nova_ExceptionData*, nova_datastruct_list_Nova_Array*);
void (*spectra_tree_nodes_operations_Nova_Assignable_virtual_Nova_onAssigned)(spectra_tree_nodes_operations_Nova_Assignable*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_Nova_Value*);
void (*spectra_tree_nodes_operations_Nova_AssignableFunctionMap_virtualfunctionMap0_Nova_onAssigned)(spectra_tree_nodes_operations_Nova_AssignableFunctionMap*, nova_exception_Nova_ExceptionData*, spectra_tree_nodes_operations_Nova_Assignable*, spectra_tree_nodes_Nova_Value*);
int (*example_Nova_Polygon_virtual_Nova_numberSides)(example_Nova_Polygon*, nova_exception_Nova_ExceptionData*);
double (*example_Nova_Polygon_virtual_Nova_calculateArea)(example_Nova_Polygon*, nova_exception_Nova_ExceptionData*);
} nova_Interface_VTable;

#endif
