NOVA_DEPS = NovaOutput.h ../../StandardLibrary/nova/NativeObject.h ../../StandardLibrary/nova/NativeSystem.h ../../StandardLibrary/nova/database/NativeDBConnector.h ../../StandardLibrary/nova/gc/NativeGC.h ../../StandardLibrary/nova/io/NativeConsole.h ../../StandardLibrary/nova/io/NativeFile.h ../../StandardLibrary/nova/network/NativeClientSocket.h ../../StandardLibrary/nova/network/NativeSocket.h ../../StandardLibrary/nova/network/NativeServerSocket.h ../../StandardLibrary/nova/security/NativeMD5.h ../../StandardLibrary/nova/star/NativeWindow.h ../../StandardLibrary/nova/thread/NativeThread.h ../../StandardLibrary/nova/time/NativeDate.h ../../StandardLibrary/nova/time/NativeTime.h
NOVA_OBJ = NovaOutput.o ../../StandardLibrary/nova/NativeObject.o ../../StandardLibrary/nova/NativeSystem.o ../../StandardLibrary/nova/database/NativeDBConnector.o ../../StandardLibrary/nova/gc/NativeGC.o ../../StandardLibrary/nova/io/NativeConsole.o ../../StandardLibrary/nova/io/NativeFile.o ../../StandardLibrary/nova/network/NativeClientSocket.o ../../StandardLibrary/nova/network/NativeSocket.o ../../StandardLibrary/nova/network/NativeServerSocket.o ../../StandardLibrary/nova/security/NativeMD5.o ../../StandardLibrary/nova/star/NativeWindow.o ../../StandardLibrary/nova/thread/NativeThread.o ../../StandardLibrary/nova/time/NativeDate.o ../../StandardLibrary/nova/time/NativeTime.o

NOVA_COMPILE_HOME = ../../Nova-C
NOVA_STDLIB_LOCATION = ../../StandardLibrary

MAKEFILE_LOCATION = $(NOVA_COMPILE_HOME)/makefile.nova

include $(MAKEFILE_LOCATION)