#include <NovaClassData.h>

nova_datastruct_vtable_Comparable nova_datastruct_vtable_Comparable_value_default = {0};
nova_datastruct_list_vtable_Iterable nova_datastruct_list_vtable_Iterable_value_default = {0};
nova_datastruct_list_vtable_Iterator nova_datastruct_list_vtable_Iterator_value_default = {0,0};
nova_datastruct_list_vtable_List nova_datastruct_list_vtable_List_value_default = {0,0,0,0,0,0,0,0,0,0,0,0,0,0};
nova_io_vtable_InputStream nova_io_vtable_InputStream_value_default = {0};
nova_operators_vtable_Equals nova_operators_vtable_Equals_value_default = {0};
nova_operators_vtable_Multiply nova_operators_vtable_Multiply_value_default = {0};
nova_primitive_number_vtable_Integer nova_primitive_number_vtable_Integer_value_default = {0};
nova_primitive_number_vtable_RealNumber nova_primitive_number_vtable_RealNumber_value_default = {0};
spectra_tree_nodes_vtable_Abstractable spectra_tree_nodes_vtable_Abstractable_value_default = {0,0};
spectra_tree_nodes_vtable_Accessible spectra_tree_nodes_vtable_Accessible_value_default = {0,0};
spectra_tree_nodes_vtable_Listener spectra_tree_nodes_vtable_Listener_value_default = {0};
spectra_tree_nodes_annotations_vtable_Annotatable spectra_tree_nodes_annotations_vtable_Annotatable_value_default = {0};
spectra_tree_nodes_annotations_vtable_Modifier spectra_tree_nodes_annotations_vtable_Modifier_value_default = {0};
spectra_tree_nodes_functions_vtable_CallableFunction spectra_tree_nodes_functions_vtable_CallableFunction_value_default = {0,0,0};
spectra_tree_nodes_generics_vtable_GenericCompatible spectra_tree_nodes_generics_vtable_GenericCompatible_value_default = {0,0};
spectra_tree_nodes_operations_vtable_Assignable spectra_tree_nodes_operations_vtable_Assignable_value_default = {0};
