#include <NovaClassData.h>

nova_datastruct_vtable_Comparable nova_datastruct_vtable_Comparable_value_default = {0};
nova_datastruct_list_vtable_Iterable nova_datastruct_list_vtable_Iterable_value_default = {0,0};
nova_datastruct_list_vtable_Iterator nova_datastruct_list_vtable_Iterator_value_default = {0,0};
nova_datastruct_list_vtable_List nova_datastruct_list_vtable_List_value_default = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
nova_datastruct_list_vtable_OrderedList nova_datastruct_list_vtable_OrderedList_value_default = {0};
nova_io_vtable_InputStream nova_io_vtable_InputStream_value_default = {0};
nova_operators_vtable_EqualsOperator nova_operators_vtable_EqualsOperator_value_default = {0};
nova_operators_vtable_MinusEqualsOperator nova_operators_vtable_MinusEqualsOperator_value_default = {0};
nova_operators_vtable_MinusOperator nova_operators_vtable_MinusOperator_value_default = {0};
nova_operators_vtable_MultiplyEqualsOperator nova_operators_vtable_MultiplyEqualsOperator_value_default = {0};
nova_operators_vtable_MultiplyOperator nova_operators_vtable_MultiplyOperator_value_default = {0};
nova_operators_vtable_NotEqualToOperator nova_operators_vtable_NotEqualToOperator_value_default = {0};
nova_operators_vtable_PlusEqualsOperator nova_operators_vtable_PlusEqualsOperator_value_default = {0};
nova_operators_vtable_PlusOperator nova_operators_vtable_PlusOperator_value_default = {0};
nova_primitive_number_vtable_Integer nova_primitive_number_vtable_Integer_value_default = {0};
nova_primitive_number_vtable_RealNumber nova_primitive_number_vtable_RealNumber_value_default = {0};
example_vtable_Polygon example_vtable_Polygon_value_default = {0};
