#ifndef FILE_stabilitytest_Nova_InnerClassStability_NOVA
#define FILE_stabilitytest_Nova_InnerClassStability_NOVA

typedef struct stabilitytest_Nova_InnerClassStability stabilitytest_Nova_InnerClassStability;
typedef struct stabilitytest_Nova_MyOuter stabilitytest_Nova_MyOuter;
typedef struct stabilitytest_Nova_InnerClassStabilityFunctionMap stabilitytest_Nova_InnerClassStabilityFunctionMap;
typedef struct stabilitytest_Nova_InnerClassStabilityPropertyMap stabilitytest_Nova_InnerClassStabilityPropertyMap;
typedef struct stabilitytest_Nova_MyOuterFunctionMap stabilitytest_Nova_MyOuterFunctionMap;
typedef struct stabilitytest_Nova_MyOuterPropertyMap stabilitytest_Nova_MyOuterPropertyMap;
typedef struct stabilitytest_Nova_MyInner stabilitytest_Nova_MyInner;
typedef struct stabilitytest_Nova_MyInnerFunctionMap stabilitytest_Nova_MyInnerFunctionMap;
typedef struct stabilitytest_Nova_MyInnerPropertyMap stabilitytest_Nova_MyInnerPropertyMap;
typedef struct stabilitytest_Nova_MyInnerPropertyMapFunctionMap stabilitytest_Nova_MyInnerPropertyMapFunctionMap;


#include <Nova.h>
#include <InterfaceVTable.h>
#include <ExceptionHandler.h>
#include <nova/exception/nova_exception_Nova_ExceptionData.h>
#include <nova/exception/nova_exception_Nova_Exception.h>
#include <nova/exception/nova_exception_Nova_DivideByZeroException.h>
#include <nova/io/nova_io_Nova_Console.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Number.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Byte.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Short.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Int.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Long.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Float.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Double.h>
#include <nova/primitive/nova_primitive_Nova_Null.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Char.h>
#include <nova/primitive/nova_primitive_Nova_Bool.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_List.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_Array.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_ImmutableArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_IntArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_CharArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_DoubleArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_IntRange.h>
#include <nova/thread/nova_thread_Nova_Thread.h>
#include <nova/thread/async/nova_thread_async_Nova_Async.h>
#include <nova/thread/async/nova_thread_async_Nova_Task.h>
#include <nova/gc/nova_gc_Nova_GC.h>
#include <nova/math/nova_math_Nova_Math.h>
#include <nova/nova_Nova_Object.h>
#include <nova/nova_Nova_String.h>
#include <nova/nova_Nova_System.h>
#include <nova/meta/nova_meta_Nova_Class.h>
#include <nova/meta/nova_meta_Nova_FunctionMap.h>
#include <nova/meta/nova_meta_Nova_PropertyMap.h>
#include <nova/regex/nova_regex_Nova_Pattern.h>
#include <stabilitytest/stabilitytest_Nova_StabilityTest.h>
#include <stabilitytest/stabilitytest_Nova_StabilityTestCase.h>
#include <stabilitytest/stabilitytest_Nova_StabilityTestCase.h>
#include <stabilitytest/stabilitytest_Nova_StabilityTestCase.h>
#include <nova/meta/nova_meta_Nova_PropertyMap.h>
#include <nova/NativeObject.h>

CCLASS_CLASS
(
	stabilitytest_Nova_InnerClassStability, 
	
	stabilitytest_InnerClassStability_Extension_VTable* vtable;
	stabilitytest_Nova_StabilityTest* stabilitytest_Nova_StabilityTestCase_Nova_program;
)

void stabilitytest_Nova_InnerClassStability_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_InnerClassStability* stabilitytest_Nova_InnerClassStability_Nova_construct(stabilitytest_Nova_InnerClassStability* this, nova_exception_Nova_ExceptionData* exceptionData, stabilitytest_Nova_StabilityTest* program);
void stabilitytest_Nova_InnerClassStability_Nova_destroy(stabilitytest_Nova_InnerClassStability** this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_InnerClassStability_Nova_this(stabilitytest_Nova_InnerClassStability* this, nova_exception_Nova_ExceptionData* exceptionData, stabilitytest_Nova_StabilityTest* program);
void stabilitytest_Nova_InnerClassStability_Nova_test(stabilitytest_Nova_InnerClassStability* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_InnerClassStability_Nova_super(stabilitytest_Nova_InnerClassStability* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	stabilitytest_Nova_MyOuter, 
	
	stabilitytest_InnerClassStability_MyOuter_Extension_VTable* vtable;
)

void stabilitytest_Nova_MyOuter_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_MyOuter* stabilitytest_Nova_MyOuter_Nova_construct(stabilitytest_Nova_MyOuter* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyOuter_Nova_destroy(stabilitytest_Nova_MyOuter** this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyOuter_Nova_test(stabilitytest_Nova_MyOuter* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyOuter_Nova_this(stabilitytest_Nova_MyOuter* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyOuter_Nova_super(stabilitytest_Nova_MyOuter* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	stabilitytest_Nova_InnerClassStabilityFunctionMap, 
	
	stabilitytest_InnerClassStability_InnerClassStabilityFunctionMap_Extension_VTable* vtable;
)

void stabilitytest_Nova_InnerClassStabilityFunctionMap_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_InnerClassStabilityFunctionMap* stabilitytest_Nova_InnerClassStabilityFunctionMap_Nova_construct(stabilitytest_Nova_InnerClassStabilityFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_InnerClassStabilityFunctionMap_Nova_destroy(stabilitytest_Nova_InnerClassStabilityFunctionMap** this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_InnerClassStabilityFunctionMap_Nova_this(stabilitytest_Nova_InnerClassStabilityFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_InnerClassStability* stabilitytest_Nova_InnerClassStabilityFunctionMap_functionMapInnerClassStabilityFunctionMap_Nova_construct(stabilitytest_Nova_InnerClassStabilityFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, stabilitytest_Nova_StabilityTest* program);
void stabilitytest_Nova_InnerClassStabilityFunctionMap_functionMap_Nova_test(stabilitytest_Nova_InnerClassStabilityFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, stabilitytest_Nova_InnerClassStability* reference);
void stabilitytest_Nova_InnerClassStabilityFunctionMap_Nova_super(stabilitytest_Nova_InnerClassStabilityFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	stabilitytest_Nova_InnerClassStabilityPropertyMap, 
	
	stabilitytest_InnerClassStability_InnerClassStabilityPropertyMap_Extension_VTable* vtable;
)

void stabilitytest_Nova_InnerClassStabilityPropertyMap_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_InnerClassStabilityPropertyMap* stabilitytest_Nova_InnerClassStabilityPropertyMap_Nova_construct(stabilitytest_Nova_InnerClassStabilityPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_InnerClassStabilityPropertyMap_Nova_destroy(stabilitytest_Nova_InnerClassStabilityPropertyMap** this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_InnerClassStabilityPropertyMap_Nova_this(stabilitytest_Nova_InnerClassStabilityPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_InnerClassStabilityPropertyMap_Nova_super(stabilitytest_Nova_InnerClassStabilityPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	stabilitytest_Nova_MyOuterFunctionMap, 
	
	stabilitytest_InnerClassStability_MyOuterFunctionMap_Extension_VTable* vtable;
)

void stabilitytest_Nova_MyOuterFunctionMap_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_MyOuterFunctionMap* stabilitytest_Nova_MyOuterFunctionMap_Nova_construct(stabilitytest_Nova_MyOuterFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyOuterFunctionMap_Nova_destroy(stabilitytest_Nova_MyOuterFunctionMap** this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyOuterFunctionMap_Nova_this(stabilitytest_Nova_MyOuterFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_MyOuter* stabilitytest_Nova_MyOuterFunctionMap_functionMapMyOuterFunctionMap_Nova_construct(stabilitytest_Nova_MyOuterFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyOuterFunctionMap_functionMap_Nova_test(stabilitytest_Nova_MyOuterFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, stabilitytest_Nova_MyOuter* reference);
void stabilitytest_Nova_MyOuterFunctionMap_Nova_super(stabilitytest_Nova_MyOuterFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	stabilitytest_Nova_MyOuterPropertyMap, 
	
	stabilitytest_InnerClassStability_MyOuterPropertyMap_Extension_VTable* vtable;
)

void stabilitytest_Nova_MyOuterPropertyMap_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_MyOuterPropertyMap* stabilitytest_Nova_MyOuterPropertyMap_Nova_construct(stabilitytest_Nova_MyOuterPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyOuterPropertyMap_Nova_destroy(stabilitytest_Nova_MyOuterPropertyMap** this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyOuterPropertyMap_Nova_this(stabilitytest_Nova_MyOuterPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyOuterPropertyMap_Nova_super(stabilitytest_Nova_MyOuterPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	stabilitytest_Nova_MyInner, 
	
	stabilitytest_InnerClassStability_MyInner_Extension_VTable* vtable;
	int stabilitytest_Nova_MyInner_Nova_x;
	struct Private_stabilitytest_Nova_MyInner* prv;
)

void stabilitytest_Nova_MyInner_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_MyInner* stabilitytest_Nova_MyInner_Nova_construct(stabilitytest_Nova_MyInner* this, nova_exception_Nova_ExceptionData* exceptionData, int x, int y);
void stabilitytest_Nova_MyInner_Nova_destroy(stabilitytest_Nova_MyInner** this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyInner_Nova_this(stabilitytest_Nova_MyInner* this, nova_exception_Nova_ExceptionData* exceptionData, int x, int y);
void stabilitytest_Nova_MyInner_Nova_super(stabilitytest_Nova_MyInner* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	stabilitytest_Nova_MyInnerFunctionMap, 
	
	stabilitytest_InnerClassStability_MyInnerFunctionMap_Extension_VTable* vtable;
)

void stabilitytest_Nova_MyInnerFunctionMap_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_MyInnerFunctionMap* stabilitytest_Nova_MyInnerFunctionMap_Nova_construct(stabilitytest_Nova_MyInnerFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyInnerFunctionMap_Nova_destroy(stabilitytest_Nova_MyInnerFunctionMap** this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyInnerFunctionMap_Nova_this(stabilitytest_Nova_MyInnerFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_MyInner* stabilitytest_Nova_MyInnerFunctionMap_functionMapMyInnerFunctionMap_Nova_construct(stabilitytest_Nova_MyInnerFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, int x, int y);
void stabilitytest_Nova_MyInnerFunctionMap_Nova_super(stabilitytest_Nova_MyInnerFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	stabilitytest_Nova_MyInnerPropertyMap, 
	
	stabilitytest_InnerClassStability_MyInnerPropertyMap_Extension_VTable* vtable;
)

void stabilitytest_Nova_MyInnerPropertyMap_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_MyInnerPropertyMap* stabilitytest_Nova_MyInnerPropertyMap_Nova_construct(stabilitytest_Nova_MyInnerPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyInnerPropertyMap_Nova_destroy(stabilitytest_Nova_MyInnerPropertyMap** this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyInnerPropertyMap_Nova_this(stabilitytest_Nova_MyInnerPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
int stabilitytest_Nova_MyInnerPropertyMap_functionMap_Nova_x(stabilitytest_Nova_MyInnerPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData, stabilitytest_Nova_MyInner* reference);
void stabilitytest_Nova_MyInnerPropertyMap_Nova_super(stabilitytest_Nova_MyInnerPropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	stabilitytest_Nova_MyInnerPropertyMapFunctionMap, 
	
	stabilitytest_InnerClassStability_MyInnerPropertyMapFunctionMap_Extension_VTable* vtable;
)

void stabilitytest_Nova_MyInnerPropertyMapFunctionMap_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
stabilitytest_Nova_MyInnerPropertyMapFunctionMap* stabilitytest_Nova_MyInnerPropertyMapFunctionMap_Nova_construct(stabilitytest_Nova_MyInnerPropertyMapFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyInnerPropertyMapFunctionMap_Nova_destroy(stabilitytest_Nova_MyInnerPropertyMapFunctionMap** this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyInnerPropertyMapFunctionMap_Nova_this(stabilitytest_Nova_MyInnerPropertyMapFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void stabilitytest_Nova_MyInnerPropertyMapFunctionMap_Nova_super(stabilitytest_Nova_MyInnerPropertyMapFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);

#endif
