#ifndef FILE_nova_datastruct_list_Nova_DoubleArray_NOVA
#define FILE_nova_datastruct_list_Nova_DoubleArray_NOVA

typedef struct nova_datastruct_list_Nova_DoubleArray nova_datastruct_list_Nova_DoubleArray;
typedef struct nova_datastruct_list_Nova_DoubleArrayFunctionMap nova_datastruct_list_Nova_DoubleArrayFunctionMap;

typedef struct nova_exception_Nova_ExceptionData nova_exception_Nova_ExceptionData;
typedef struct nova_datastruct_list_Nova_DoubleArray nova_datastruct_list_Nova_DoubleArray;
typedef struct nova_Nova_Object nova_Nova_Object;

typedef double (*nova_datastruct_list_Nova_DoubleArray_closure161_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef double (*nova_datastruct_list_Nova_DoubleArray_closure162_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef double (*nova_datastruct_list_Nova_DoubleArray_closure163_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef double (*nova_datastruct_list_Nova_DoubleArray_closure164_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_DoubleArray_closure165_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_DoubleArray_closure166_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_DoubleArray_closure167_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_DoubleArray_closure168_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef void (*nova_datastruct_list_Nova_DoubleArray_closure169_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef void (*nova_datastruct_list_Nova_DoubleArray_closure170_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef void (*nova_datastruct_list_Nova_DoubleArray_closure171_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef void (*nova_datastruct_list_Nova_DoubleArray_closure172_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure173_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure174_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure175_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure176_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure177_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure178_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure179_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure180_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure181_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure182_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure183_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure184_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure185_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure186_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure187_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArray_closure188_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef double (*nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure432_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef nova_Nova_Object* (*nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure433_Nova_mapFunc)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef void (*nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure434_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure435_Nova_anyFunc)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure436_Nova_allFunc)(void*, nova_exception_Nova_ExceptionData*, double, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure437_Nova_filterFunc)(void*, nova_exception_Nova_ExceptionData*, double, int, nova_datastruct_list_Nova_DoubleArray*, void*);
typedef char (*nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure438_Nova_func)(void*, nova_exception_Nova_ExceptionData*, double, void*);

#include <Nova.h>
#include <InterfaceVTable.h>
#include <ExceptionHandler.h>
#include <nova/exception/nova_exception_Nova_ExceptionData.h>
#include <nova/exception/nova_exception_Nova_Exception.h>
#include <nova/exception/nova_exception_Nova_DivideByZeroException.h>
#include <nova/io/nova_io_Nova_Console.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Number.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Byte.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Short.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Int.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Long.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Float.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Double.h>
#include <nova/primitive/nova_primitive_Nova_Null.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Char.h>
#include <nova/primitive/nova_primitive_Nova_Bool.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_List.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_Array.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_ImmutableArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_IntArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_CharArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_DoubleArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_IntRange.h>
#include <nova/thread/nova_thread_Nova_Thread.h>
#include <nova/thread/async/nova_thread_async_Nova_Async.h>
#include <nova/thread/async/nova_thread_async_Nova_Task.h>
#include <nova/gc/nova_gc_Nova_GC.h>
#include <nova/math/nova_math_Nova_Math.h>
#include <nova/nova_Nova_Object.h>
#include <nova/nova_Nova_String.h>
#include <nova/nova_Nova_System.h>
#include <nova/meta/nova_meta_Nova_Class.h>
#include <nova/meta/nova_meta_Nova_FunctionMap.h>
#include <nova/regex/nova_regex_Nova_Pattern.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_DoubleArrayIterator.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_Array.h>
#include <nova/datastruct/nova_datastruct_Nova_Comparable.h>
#include <nova/operators/nova_operators_Nova_PlusOperator.h>
#include <nova/operators/nova_operators_Nova_PlusEqualsOperator.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_ArrayIterator.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_OrderedList.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_List.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_OrderedList.h>
#include <nova/operators/nova_operators_Nova_PlusOperator.h>
#include <nova/operators/nova_operators_Nova_PlusEqualsOperator.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_Iterable.h>
#include <nova/NativeObject.h>

CCLASS_CLASS
(
	nova_datastruct_list_Nova_DoubleArray, 
	
	nova_datastruct_list_DoubleArray_Extension_VTable* vtable;
	int nova_datastruct_list_Nova_Array_Nova_capacity;
	int nova_datastruct_list_Nova_Array_Nova_count;
	int nova_datastruct_list_Nova_Array_Nova_position;
	nova_Nova_Object** nova_datastruct_list_Nova_Array_Nova_data;
)

void nova_datastruct_list_Nova_DoubleArray_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArray_0_Nova_construct(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArray_1_Nova_construct(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, double* data, int count);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArray_2_Nova_construct(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, int count);
void nova_datastruct_list_Nova_DoubleArray_Nova_destroy(nova_datastruct_list_Nova_DoubleArray** this, nova_exception_Nova_ExceptionData* exceptionData);
void nova_datastruct_list_Nova_DoubleArray_Nova_this(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData);
void nova_datastruct_list_Nova_DoubleArray_0_Nova_this(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, double* data, int count);
void nova_datastruct_list_Nova_DoubleArray_1_Nova_this(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, int count);
double nova_datastruct_list_Nova_DoubleArray_Nova_sum(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray_closure164_Nova_func nova_datastruct_list_Nova_DoubleArray_Nova_func, void* nova_datastruct_list_Nova_DoubleArray_ref_Nova_func, void* func_context);
nova_datastruct_list_Nova_Array* nova_datastruct_list_Nova_DoubleArray_Nova_map(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray_closure168_Nova_mapFunc nova_datastruct_list_Nova_DoubleArray_Nova_mapFunc, void* nova_datastruct_list_Nova_DoubleArray_ref_Nova_mapFunc, void* mapFunc_context);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArray_Nova_forEach(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray_closure172_Nova_func nova_datastruct_list_Nova_DoubleArray_Nova_func, void* nova_datastruct_list_Nova_DoubleArray_ref_Nova_func, void* func_context);
char nova_datastruct_list_Nova_DoubleArray_Nova_any(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray_closure176_Nova_anyFunc nova_datastruct_list_Nova_DoubleArray_Nova_anyFunc, void* nova_datastruct_list_Nova_DoubleArray_ref_Nova_anyFunc, void* anyFunc_context);
char nova_datastruct_list_Nova_DoubleArray_Nova_all(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray_closure180_Nova_allFunc nova_datastruct_list_Nova_DoubleArray_Nova_allFunc, void* nova_datastruct_list_Nova_DoubleArray_ref_Nova_allFunc, void* allFunc_context);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArray_Nova_filter(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray_closure184_Nova_filterFunc nova_datastruct_list_Nova_DoubleArray_Nova_filterFunc, void* nova_datastruct_list_Nova_DoubleArray_ref_Nova_filterFunc, void* filterFunc_context);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArray_Nova_take(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, int howMany);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArray_Nova_skip(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, int howMany);
double nova_datastruct_list_Nova_DoubleArray_Nova_firstWhere(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray_closure188_Nova_func nova_datastruct_list_Nova_DoubleArray_Nova_func, void* nova_datastruct_list_Nova_DoubleArray_ref_Nova_func, void* func_context);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArray_Nova_reverse(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* nova_datastruct_list_Nova_DoubleArray_Nova_join(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, nova_Nova_String* delimiter);
double nova_datastruct_list_Nova_DoubleArray_Nova_get(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, int index);
double nova_datastruct_list_Nova_DoubleArray_Nova_set(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData, int index, double value);
nova_datastruct_list_Nova_DoubleArrayIterator* nova_datastruct_list_Nova_DoubleArray_Accessor_Nova_iterator(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData);
double nova_datastruct_list_Nova_DoubleArray_Accessor_Nova_first(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData);
double nova_datastruct_list_Nova_DoubleArray_Accessor_Nova_last(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData);
void nova_datastruct_list_Nova_DoubleArray_Nova_super(nova_datastruct_list_Nova_DoubleArray* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	nova_datastruct_list_Nova_DoubleArrayFunctionMap, 
	
	nova_datastruct_list_DoubleArray_DoubleArrayFunctionMap_Extension_VTable* vtable;
)

void nova_datastruct_list_Nova_DoubleArrayFunctionMap_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_DoubleArrayFunctionMap* nova_datastruct_list_Nova_DoubleArrayFunctionMap_Nova_construct(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void nova_datastruct_list_Nova_DoubleArrayFunctionMap_Nova_destroy(nova_datastruct_list_Nova_DoubleArrayFunctionMap** this, nova_exception_Nova_ExceptionData* exceptionData);
void nova_datastruct_list_Nova_DoubleArrayFunctionMap_Nova_this(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMapDoubleArrayFunctionMap0_Nova_construct(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMapDoubleArrayFunctionMap1_Nova_construct(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, double* data, int count);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMapDoubleArrayFunctionMap2_Nova_construct(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, int count);
double nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_sum(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference, nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure432_Nova_func nova_datastruct_list_Nova_DoubleArrayFunctionMap_Nova_func, void* nova_datastruct_list_Nova_DoubleArrayFunctionMap_ref_Nova_func, void* func_context);
nova_datastruct_list_Nova_Array* nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_map(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference, nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure433_Nova_mapFunc nova_datastruct_list_Nova_DoubleArrayFunctionMap_Nova_mapFunc, void* nova_datastruct_list_Nova_DoubleArrayFunctionMap_ref_Nova_mapFunc, void* mapFunc_context);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_forEach(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference, nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure434_Nova_func nova_datastruct_list_Nova_DoubleArrayFunctionMap_Nova_func, void* nova_datastruct_list_Nova_DoubleArrayFunctionMap_ref_Nova_func, void* func_context);
char nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_any(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference, nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure435_Nova_anyFunc nova_datastruct_list_Nova_DoubleArrayFunctionMap_Nova_anyFunc, void* nova_datastruct_list_Nova_DoubleArrayFunctionMap_ref_Nova_anyFunc, void* anyFunc_context);
char nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_all(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference, nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure436_Nova_allFunc nova_datastruct_list_Nova_DoubleArrayFunctionMap_Nova_allFunc, void* nova_datastruct_list_Nova_DoubleArrayFunctionMap_ref_Nova_allFunc, void* allFunc_context);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_filter(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference, nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure437_Nova_filterFunc nova_datastruct_list_Nova_DoubleArrayFunctionMap_Nova_filterFunc, void* nova_datastruct_list_Nova_DoubleArrayFunctionMap_ref_Nova_filterFunc, void* filterFunc_context);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_take(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference, int howMany);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_skip(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference, int howMany);
double nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_firstWhere(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference, nova_datastruct_list_Nova_DoubleArrayFunctionMap_closure438_Nova_func nova_datastruct_list_Nova_DoubleArrayFunctionMap_Nova_func, void* nova_datastruct_list_Nova_DoubleArrayFunctionMap_ref_Nova_func, void* func_context);
nova_datastruct_list_Nova_DoubleArray* nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_reverse(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference);
nova_Nova_String* nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_join(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference, nova_Nova_String* delimiter);
double nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_get(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference, int index);
double nova_datastruct_list_Nova_DoubleArrayFunctionMap_functionMap_Nova_set(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_DoubleArray* reference, int index, double value);
void nova_datastruct_list_Nova_DoubleArrayFunctionMap_Nova_super(nova_datastruct_list_Nova_DoubleArrayFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);

#endif
