#ifndef FILE_nova_datastruct_list_Nova_Queue_NOVA
#define FILE_nova_datastruct_list_Nova_Queue_NOVA

typedef struct nova_datastruct_list_Nova_Queue nova_datastruct_list_Nova_Queue;
typedef struct nova_datastruct_list_Nova_QueueFunctionMap nova_datastruct_list_Nova_QueueFunctionMap;
typedef struct nova_datastruct_list_Nova_QueuePropertyMap nova_datastruct_list_Nova_QueuePropertyMap;


#include <Nova.h>
#include <InterfaceVTable.h>
#include <ExceptionHandler.h>
#include <nova/exception/nova_exception_Nova_ExceptionData.h>
#include <nova/exception/nova_exception_Nova_Exception.h>
#include <nova/exception/nova_exception_Nova_DivideByZeroException.h>
#include <nova/io/nova_io_Nova_Console.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Number.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Byte.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Short.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Int.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Long.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Float.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Double.h>
#include <nova/primitive/nova_primitive_Nova_Null.h>
#include <nova/primitive/number/nova_primitive_number_Nova_Char.h>
#include <nova/primitive/nova_primitive_Nova_Bool.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_List.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_Array.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_ImmutableArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_IntArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_CharArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_DoubleArray.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_IntRange.h>
#include <nova/thread/nova_thread_Nova_Thread.h>
#include <nova/thread/async/nova_thread_async_Nova_Async.h>
#include <nova/thread/async/nova_thread_async_Nova_Task.h>
#include <nova/gc/nova_gc_Nova_GC.h>
#include <nova/math/nova_math_Nova_Math.h>
#include <nova/nova_Nova_Object.h>
#include <nova/nova_Nova_String.h>
#include <nova/nova_Nova_System.h>
#include <nova/meta/nova_meta_Nova_Class.h>
#include <nova/meta/nova_meta_Nova_FunctionMap.h>
#include <nova/meta/nova_meta_Nova_PropertyMap.h>
#include <nova/regex/nova_regex_Nova_Pattern.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_ArrayIterator.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_List.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_Iterable.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_List.h>
#include <nova/datastruct/list/nova_datastruct_list_Nova_Iterable.h>
#include <nova/NativeObject.h>

CCLASS_CLASS
(
	nova_datastruct_list_Nova_Queue, 
	
	nova_datastruct_list_Queue_Extension_VTable* vtable;
	int nova_datastruct_list_Nova_Queue_Nova_count;
	nova_Nova_Object* nova_datastruct_list_Nova_Queue_Nova_first;
	nova_Nova_Object* nova_datastruct_list_Nova_Queue_Nova_last;
	struct Private_nova_datastruct_list_Nova_Queue* prv;
)

void nova_datastruct_list_Nova_Queue_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_Queue* nova_datastruct_list_Nova_Queue_0_Nova_construct(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_Queue* nova_datastruct_list_Nova_Queue_1_Nova_construct(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Array* data);
void nova_datastruct_list_Nova_Queue_Nova_destroy(nova_datastruct_list_Nova_Queue** this, nova_exception_Nova_ExceptionData* exceptionData);
void nova_datastruct_list_Nova_Queue_Nova_this(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData);
void nova_datastruct_list_Nova_Queue_0_Nova_this(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Array* data);
nova_Nova_Object* nova_datastruct_list_Nova_Queue_Nova_dequeue(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_Array* nova_datastruct_list_Nova_Queue_Nova_enqueue(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData, nova_Nova_Object* element);
nova_datastruct_list_Nova_Queue* nova_datastruct_list_Nova_Queue_Nova_reverse(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_String* nova_datastruct_list_Nova_Queue_Nova_toString(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData);
int nova_datastruct_list_Nova_Queue_Accessor_Nova_size(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData);
char nova_datastruct_list_Nova_Queue_Accessor_Nova_empty(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_ArrayIterator* nova_datastruct_list_Nova_Queue_Accessor_Nova_iterator(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData);
int nova_datastruct_list_Nova_Queue_Accessorfunc_Nova_count(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData);
int nova_datastruct_list_Nova_Queue_Mutatorfunc0_Nova_count(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData, int value);
nova_Nova_Object* nova_datastruct_list_Nova_Queue_Accessorfunc_Nova_first(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_Object* nova_datastruct_list_Nova_Queue_Mutatorfunc0_Nova_first(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData, nova_Nova_Object* value);
nova_Nova_Object* nova_datastruct_list_Nova_Queue_Accessorfunc_Nova_last(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_Nova_Object* nova_datastruct_list_Nova_Queue_Mutatorfunc0_Nova_last(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData, nova_Nova_Object* value);
void nova_datastruct_list_Nova_Queue_Nova_super(nova_datastruct_list_Nova_Queue* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	nova_datastruct_list_Nova_QueueFunctionMap, 
	
	nova_datastruct_list_Queue_QueueFunctionMap_Extension_VTable* vtable;
)

void nova_datastruct_list_Nova_QueueFunctionMap_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_QueueFunctionMap* nova_datastruct_list_Nova_QueueFunctionMap_Nova_construct(nova_datastruct_list_Nova_QueueFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void nova_datastruct_list_Nova_QueueFunctionMap_Nova_destroy(nova_datastruct_list_Nova_QueueFunctionMap** this, nova_exception_Nova_ExceptionData* exceptionData);
void nova_datastruct_list_Nova_QueueFunctionMap_Nova_this(nova_datastruct_list_Nova_QueueFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_Queue* nova_datastruct_list_Nova_QueueFunctionMap_functionMapQueueFunctionMap0_Nova_construct(nova_datastruct_list_Nova_QueueFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_Queue* nova_datastruct_list_Nova_QueueFunctionMap_functionMapQueueFunctionMap1_Nova_construct(nova_datastruct_list_Nova_QueueFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Array* data);
nova_Nova_Object* nova_datastruct_list_Nova_QueueFunctionMap_functionMap_Nova_dequeue(nova_datastruct_list_Nova_QueueFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Queue* reference);
nova_datastruct_list_Nova_Array* nova_datastruct_list_Nova_QueueFunctionMap_functionMap_Nova_enqueue(nova_datastruct_list_Nova_QueueFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Queue* reference, nova_Nova_Object* element);
nova_datastruct_list_Nova_Queue* nova_datastruct_list_Nova_QueueFunctionMap_functionMap_Nova_reverse(nova_datastruct_list_Nova_QueueFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Queue* reference);
nova_Nova_String* nova_datastruct_list_Nova_QueueFunctionMap_functionMap_Nova_toString(nova_datastruct_list_Nova_QueueFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Queue* reference);
void nova_datastruct_list_Nova_QueueFunctionMap_Nova_super(nova_datastruct_list_Nova_QueueFunctionMap* this, nova_exception_Nova_ExceptionData* exceptionData);

CCLASS_CLASS
(
	nova_datastruct_list_Nova_QueuePropertyMap, 
	
	nova_datastruct_list_Queue_QueuePropertyMap_Extension_VTable* vtable;
)

void nova_datastruct_list_Nova_QueuePropertyMap_Nova_init_static(nova_exception_Nova_ExceptionData* exceptionData);
nova_datastruct_list_Nova_QueuePropertyMap* nova_datastruct_list_Nova_QueuePropertyMap_Nova_construct(nova_datastruct_list_Nova_QueuePropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
void nova_datastruct_list_Nova_QueuePropertyMap_Nova_destroy(nova_datastruct_list_Nova_QueuePropertyMap** this, nova_exception_Nova_ExceptionData* exceptionData);
void nova_datastruct_list_Nova_QueuePropertyMap_Nova_this(nova_datastruct_list_Nova_QueuePropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);
int nova_datastruct_list_Nova_QueuePropertyMap_functionMap_Nova_size(nova_datastruct_list_Nova_QueuePropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Queue* reference);
char nova_datastruct_list_Nova_QueuePropertyMap_functionMap_Nova_empty(nova_datastruct_list_Nova_QueuePropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Queue* reference);
nova_datastruct_list_Nova_ArrayIterator* nova_datastruct_list_Nova_QueuePropertyMap_functionMap0_Nova_iterator(nova_datastruct_list_Nova_QueuePropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Queue* reference);
int nova_datastruct_list_Nova_QueuePropertyMap_functionMap0_Nova_count(nova_datastruct_list_Nova_QueuePropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Queue* reference);
nova_Nova_Object* nova_datastruct_list_Nova_QueuePropertyMap_functionMap0_Nova_first(nova_datastruct_list_Nova_QueuePropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Queue* reference);
nova_Nova_Object* nova_datastruct_list_Nova_QueuePropertyMap_functionMap0_Nova_last(nova_datastruct_list_Nova_QueuePropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData, nova_datastruct_list_Nova_Queue* reference);
void nova_datastruct_list_Nova_QueuePropertyMap_Nova_super(nova_datastruct_list_Nova_QueuePropertyMap* this, nova_exception_Nova_ExceptionData* exceptionData);

#endif
